Repository esphome-econet/esphome-econet, pull requests merged in 2023-12, with the labels that each got.

#257 Add Github Actions Relese Workflow
  .github/workflows/release-firmware.yml
Labels: enhancement

#259 fix(#258): Use PAT for release generation.
  .github/workflows/release-firmware.yml
Labels: bug

#263 chore: Update dependabot config to reduce frequency and number of updates.
  .github/dependabot.yml
Labels: dependencies

#265 fix: Dependabot config file failing to parse.
  .github/dependabot.yml
Labels: bug

#267 chore: Removing executable file perms from a couple of files that shouldn't have had them
  .yamllint
  econet_hvac_odu.yaml
Labels: bug

#269 chore: Remove minor versions from github-actions dependencies
  .github/workflows/build-and-publish.yml
  .github/workflows/build-nightly.yml
  .github/workflows/build.yml
  .github/workflows/release-firmware.yml
Labels: enhancement

#256 feat: Support for switch read/write to specific src_address
  components/econet/econet.cpp
  components/econet/econet.h
  components/econet/switch/__init__.py
  components/econet/switch/econet_switch.cpp
Labels: enhancement

#298 Remove unsupported entities (alarm_beep and screen_lock) from tankless
  econet_tankless_water_heater.yaml
Labels: bug

#297 Add gas usage entities to gas tankless water heaters
  econet_tankless_water_heater.yaml
Labels: enhancement

#303 fix(#302): Use HASS-Standard Units on Furnace Entities
  econet_hvac_air_handler.yaml
  econet_hvac_furnace.yaml
  econet_hvac_odu.yaml
Labels: bug

#306 fix(#307): Fixing decimal precision after conversion to mA
  econet_hvac_furnace.yaml
Labels: bug

#308 fix: Added missing units to AFUE sensor
  econet_hvac_furnace.yaml
Labels: bug
