Repository esphome-econet/esphome-econet, pull requests merged in 2023-11, with the labels that each got.

#140 Moving minimum esphome version to 2023.8.0
  econet_base.yaml
Labels: bug, dependencies

#139 Add spellchecking.
  .pre-commit-config.yaml
  setup.cfg
Labels: enhancement

#142 Switch to Matrixing for Faster Build Checks and Full Config Validation
  .github/workflows/build.yml
Labels: enhancement

#141 Initial workflow for publishing of pre-built firmware
  .github/workflows/build-and-publish.yml
  build-yaml/esp32.yaml
  build-yaml/esp8266.yaml
Labels: enhancement

#190 Readme overhaul
  README.md
  example-local.yaml
Labels: documentation

#191 Avoid associating responses to the wrong request when we drop messages and fix parsing of requested objects with 0x00 in the middle of their name
  components/econet/econet.cpp
Labels: bug

#217 Updating name substitution to match build workflow.
  econet_hvac_air_handler.yaml
  econet_hvac_furnace.yaml
Labels: bug
