Repository esphome-econet/esphome-econet, pull requests merged in 2024-02, with the labels that each got.

#187 Initial implementation of HVAC zone control and diagnostics
  econet_hvac.yaml
  example-local.yaml
  hvac-zone-yaml/econet_hvac_zone1.yaml
  hvac-zone-yaml/econet_hvac_zone123status.yaml
  hvac-zone-yaml/econet_hvac_zone2.yaml
  hvac-zone-yaml/econet_hvac_zone3.yaml
  hvac-zone-yaml/econet_hvac_zone3_electronicbypass.yaml
  hvac-zone-yaml/econet_hvac_zone456status.yaml
  hvac-zone-yaml/econet_hvac_zone6_electronicbypass.yaml
  hvac-zone-yaml/econet_hvac_zone_sensors_template.yaml
  hvac-zone-yaml/econet_hvac_zone_template.yaml
  hvac-zone-yaml/remote-hvac-example.yaml
Labels: enhancement

#341 fix(340): Base ODU_DEFROST binary_sensor on internal float sensor
  econet_hvac_odu.yaml
Labels: bug

#348 docs: Update README to reference multi-zone support
  README.md
Labels: documentation

#357 chore(deps): Remove specific build-action version now that v1 tag is fixed
  .github/workflows/build.yml
Labels: dependencies

#355 feat: Add sensor for microcontroller current time
  econet_base.yaml
Labels: enhancement

#359 fix: Microcontroller Datetime showing start of 2000 instead of unknown
  econet_base.yaml
Labels: bug

#358 fix: use correct address for homeassistant_read
  components/econet/econet.cpp
Labels: bug

#360 feat: synchronize clock
  econet_base.yaml
Labels: enhancement

#363 ci: Adding esphome build caching for performance
  .github/workflows/build.yml
Labels: enhancement
